### ISSUE TITLE
Feltöltve

### ISSUE THREAD

**Issue by szabopown** [Teaching-projects/SZE-FordProg-Scientific-Calculator#1]
Szia Máté!

Elkészültem a feladattal, kérlek nézd meg, hogy elfogadható-e ebben a formában.

**Comment by hegyhati** [comment]
Csak egy feedback, mert mar ket napos a dolog: nincs elveszve, csak meg nemvolt idom ra. Valoszinuleg holnap nezem meg.

**Comment by szabopown** [comment]
Rendben, köszönöm előre is

**Comment by hegyhati** [comment]
Na, meglestem, olyan sok ido nem kellett hozza :-) Szoval a kerdes, hogy hanyas jegyre hajtasz. A harmas ezzel megvan, de ha jobb jegyet szeretnel, akkor valami kicsit osszetettebb dolgot bele kellene tenni. 

Illetve most nincs elottem a negyjegyu, de az `atan` szerintem nem igy mukodik ;-)

**Comment by szabopown** [comment]
Rendben köszönöm, alapesetben nem elégednék meg a hármassal, de sok külső tényező is közbejött.
Így köszönöm elfogadom a hármast.
Atan függvény javítva

**Comment by hegyhati** [comment]
Rendben, akkor jelentkezz fel a vizsgara, ez majd oda beirom, egyeb teendod nincsen, kitartast minden mashoz!
